### ISSUE TITLE
422 when trying to upload

### ISSUE THREAD

**Issue by glpzzz** [shihanng/devto#8]
My command:

`devto submit my-article.md --api-key=thekey --published`

Result: 

`Error: article: create article in dev.to: 422 Unprocessable Entity`

**Comment by shihanng** [comment]
Hi @glpzzz, thank you for raising this issue. Could you check if your Markdown file contains Jekyll front matter:

```
---
title: 
published: false
description: 
tags: 
cover_image:
---

Begin writing here...
```

It should at least contain the `title` field else the API will return `422 Unprocessable Entity`. Please let me know if this helps? Thank you.

**Comment by glpzzz** [comment]
My previous .md doesn't include the front matter. Now I tested with frontmatter and all good. Thanks!

**Comment by glpzzz** [comment]
> Hi @glpzzz, thank you for raising this issue. Could you check if your Markdown file contains Jekyll front matter:
> 
> ```
> ---
> title: 
> published: false
> description: 
> tags: 
> cover_image:
> ---
> 
> Begin writing here...
> ```
> 
> It should at least contain the `title` field else the API will return `422 Unprocessable Entity`. Please let me know if this helps? Thank you.

Should this requirement be on the README.md of this repo?

**Comment by shihanng** [comment]
> Should this requirement be on the README.md of this repo?

That's a good idea. Will keep this issue open until it is added.
